// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wepqppbvhqfmeypfstgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcHFwcGJ2aHFmbWV5cGZzdGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTA1MjksImV4cCI6MjA3Mzc4NjUyOX0.SEl0og3UTthJun7sIwkyGdl3Zjl6RLqBGEBCnDfYpYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});